### ISSUE TITLE
Error: Unknown command: cask at Get list of apps installed with cask

### ISSUE THREAD

**Issue by ianheggie** [geerlingguy/ansible-role-homebrew#11]
I was getting a failure when the cask list was being retrieved. It appears to be a conflict between what brew assumes is set up and the environment ssh sets up when running commands. 

I have fixed it by changing the command from brew cask to brew-cask:
```
# Cask.
- name: Get list of apps installed with cask.
  command: "{{ homebrew_brew_bin_path }}/brew-cask list"
  register: homebrew_cask_list
  always_run: yes
  changed_when: false
```
Log before fix:
```
TASK: [geerlingguy.homebrew | Ensure configured taps are tapped.] ************* 
ok: [post1] => (item=caskroom/cask)

TASK: [geerlingguy.homebrew | Ensure configured homebrew packages are installed.] *** 
ok: [post1] => (item=coreutils)
ok: [post1] => (item=git)
ok: [post1] => (item=parallel)
ok: [post1] => (item=dcraw)
ok: [post1] => (item=jpeg)
ok: [post1] => (item=graphicsmagick)
ok: [post1] => (item=the_silver_searcher)
ok: [post1] => (item=brew-cask)

TASK: [geerlingguy.homebrew | Upgrade all homebrew packages (if configured).] *** 
skipping: [post1]

TASK: [geerlingguy.homebrew | Get list of apps installed with cask.] ********** 
failed: [post1] => {"changed": false, "cmd": ["/usr/local/bin/brew", "cask", "list"], "delta": "0:00:00.232802", "end": "2015-08-10 20:53:43.307777", "rc": 1, "start": "2015-08-10 20:53:43.074975", "stdout_lines": [], "warnings": []}
stderr: Error: Unknown command: cask

FATAL: all hosts have already failed -- aborting
```

I noted that sshing to the host then running the command works, but calling the command directly via ssh does not work:
```
$ ssh post1 "/usr/local/bin/brew cask list"
Error: Unknown command: cask
$ ssh post1
Last login: Mon Aug 10 20:58:26 2015 from 10.10.0.1
Post1:~ post1$ /usr/local/bin/brew cask list
Warning: nothing to list
Post1:~ post1$ 
```

**Comment by ianheggie** [comment]
When I expanded this to run on other systems, I ended up having to run the list command manually to set permissions as ' Get list of apps installed with cask' froze. I am guessing it needs to run as sudo?

```
$ ssh post-mini
Last login: Mon Aug 10 21:22:43 2015 from 10.10.0.4
$ brew-cask list
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
Warning: nothing to list
$
```

the site.yml file includes:
```
- hosts: osx
  gather_facts: False
  sudo: false
  vars:
    homebrew_upgrade_all_packages: no
    homebrew_taps:
      - caskroom/cask
    homebrew_installed_packages:
      - coreutils
      - git
      - parallel
      - dcraw
      - jpeg
      - graphicsmagick
      - the_silver_searcher
      - brew-cask
    homebrew_cask_apps: [ ]
  roles:
  #- { role: after_effects, tags: [ 'after_effects' ] }
  - { role: geerlingguy.homebrew, tags: [ 'homebrew' ] }
```

**Comment by fubarhouse** [comment]
I can confirm this as an issue.
I've tried a few things, and I've not been able to resolve it...

**Comment by geerlingguy** [comment]
Just as an FYI, the main place I use this playbook is: https://github.com/geerlingguy/mac-dev-playbook — I don't run as sudo in there, just as my normal user account...

**Comment by orangewolf** [comment]
This command works when run with localhost as the target, but not when run over SSH.  At least in Ansible 1.9.2.  The following command appears to work in both places

```yaml
- name: Get list of apps installed with cask.
  command: >
    bash -l -c '{{ homebrew_brew_bin_path }}/brew cask list'
  register: homebrew_cask_list
  always_run: yes
  changed_when: false
```
