### ISSUE TITLE
homebrew module loop deprecation warning 

### ISSUE THREAD

**Issue by ksylvan** [geerlingguy/ansible-role-homebrew#110]
The `homebrew` module used by this role is capable of installing multiple packages without a loop construct.

```
TASK [geerlingguy.homebrew : Ensure configured homebrew packages are installed.] ***********************
[DEPRECATION WARNING]: Invoking "homebrew" only once while using a loop via squash_actions is 
deprecated. Instead of using a loop to supply multiple items and specifying `name: {{ item.name | 
default(item) }}`, please use `name: u'{{ homebrew_installed_packages }}'` and remove the loop. This 
feature will be removed in version 2.11. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

The problem is, the stanza dealing with installing packages via brew needs to also deal with the `install_options` variant of specifying the `homebew_installed_packages`

```
# Brew.
- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  with_items: "{{ homebrew_installed_packages }}"
  notify:
    - Clear homebrew cache
```
