### ISSUE TITLE
ansible_pkg_mgr is unknown after executing this role

### ISSUE THREAD

**Issue by GlaIZier** [geerlingguy/ansible-role-homebrew#117]
Hello there! 

First of all, thank your for your outstanding role!

The reason I decided to open an issue is my current project. I'm working on automation of initialization of my working environment. After applying this role, I'm trying to install sdkman using another role. The code looks like this there: 
```
- name: Install system packages
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present
  become: yes
  tags:
    - sdkman_privilege
```

On this line this code fails as ansible_pkg_mgr is 'unknown' in a travis-ci environment. Homebrew was removed on a Travis instance the same way as [here](https://github.com/geerlingguy/mac-dev-playbook/blob/master/.travis.yml)

Could you be so kind as to assist? As I don't use Ansible very often, I'm not an expert and not sure that this is a bug of your role. Did I miss something?
