### ISSUE TITLE
Task : Force update brew after installation Failed

### ISSUE THREAD

**Issue by binnythomas-1989** [geerlingguy/ansible-role-homebrew#132]
Running the ansible task 
TASK [Homebrew : Force update brew after installation.]  Failed with the below error.

```
"Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...\nerror: RPC failed; curl 18 transfer closed with outstanding read data remaining\nfatal: the remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack failed\nError: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` exited with 128.\nError: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.", "stderr_lines": ["Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...", "error: RPC failed;
```

I  have fixed it by adding the following lines to manually download the core and cask, which i believe is being done by

```
    - name: Check brew core package exist
      stat:
        path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
      register: brew_core_dir

    - name: Check brew cask package exist
      stat:
        path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
      register: brew_cask_dir

    - name: Adding brew core packages
      command: git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --depth=1      
      when: not brew_core_dir.stat.exists

    - name: Adding brew cask packages
      command: git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --depth=1
      when: not brew_cask_dir.stat.exists 
```
