### ISSUE TITLE
Task: brew permissions issue

### ISSUE THREAD

**Issue by issmirnov** [geerlingguy/ansible-role-homebrew#135]
The first run of the playbook errorred out:

```

TASK [geerlingguy.homebrew : Force update brew after installation.] ******************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/brew", "update", "--force"], "delta": "0:01:26.618295", "end": "2020-05-27 14:30:13.679602", "msg": "non-zero return code", "rc": 1, "start": "2020-05-27 14:28:47.061307", "stderr": "Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...\nError: Failed to link all completions, docs and manpages:\n  Permission denied @ rb_file_s_symlink - (../../../Homebrew/manpages/README.md, /usr/local/share/man/man1/README.md)", "stderr_lines": ["Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...", "Error: Failed to link all completions, docs and manpages:", "  Permission denied @ rb_file_s_symlink - (../../../Homebrew/manpages/README.md, /usr/local/share/man/man1/README.md)"], "stdout": "\u0007==> Homebrew has enabled anonymous aggregate formulae and cask analytics.\nRead the analytics documentation (and how to opt-out) here:\n  https://docs.brew.sh/Analytics\nNo analytics have been recorded yet (or will be during this `brew` run).\n\n==> Homebrew is run entirely by unpaid volunteers. Please consider donating:\n  https://github.com/Homebrew/brew#donations\n==> Tapping homebrew/core\nTapped 2 commands and 5024 formulae (5,280 files, 320.0MB).\nAlready up-to-date.", "stdout_lines": ["\u0007==> Homebrew has enabled anonymous aggregate formulae and cask analytics.", "Read the analytics documentation (and how to opt-out) here:", "  https://docs.brew.sh/Analytics", "No analytics have been recorded yet (or will be during this `brew` run).", "", "==> Homebrew is run entirely by unpaid volunteers. Please consider donating:", "  https://github.com/Homebrew/brew#donations", "==> Tapping homebrew/core", "Tapped 2 commands and 5024 formulae (5,280 files, 320.0MB).", "Already up-to-date."]}
```

After running `sudo chown -R $(whoami):admin $(brew --prefix)/*` and restarting, the playbook was able to complete.

I suggest adding a permissions check in the role, and run the `chown` on the user's behalf if needed.

**Comment by basictheprogram** [comment]
I think this issue is related. Posting here, but I can move it to it's own issue. Seem like the role is making changes that cause `brew doctor` to throw warnings.

Before ansible-role-homebrew is run
```
$ brew doctor
Your system is ready to brew.
```
Running this playbook
```yaml
---
- name: Install packer image build node
  hosts: all
  become: true

  vars:
    homebrew_user: "{{ ansible_user_id }}"
    homebrew_group: "{{ ansible_user_gid }}"
    homebrew_upgrade_all_packages: true
    homebrew_installed_packages:
      - bash
      - git
      - openssh
      - packer
      - "python@3.8"
      - rsync
      - sqlite
      - terraform
    roles:
    - geerlingguy.homebrew
```
Although `brew doctor` says things are ok. The ansible run finds this problem.
```
TASK [geerlingguy.homebrew : Upgrade all homebrew packages (if configured).] ***
fatal: [macos-packer]: FAILED! => {"changed": false, "msg": "Error: Can't create update lock in /usr/local/var/homebrew/locks!\nFix permissions by running:\n  sudo chown -R $(whoami) /usr/local/var/homebrew"}
```
