### ISSUE TITLE
Installing casks requiring sudo password?

### ISSUE THREAD

**Issue by drew-kun** [geerlingguy/ansible-role-homebrew#147]
Hi and thank you very much for this role!

One thing I do not understand is how can the one use it in order to install casks which require sudo password input during cask installation...

Examples of such casks are: Virtualbox, Wireshark, Zenmap, Mactex etc.

Every time I run my plays, when the task comes to install those casks it hangs infinitely(((.

I wonder if there anything can be done to work around this issue?

I found this [community collection](https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_cask_module.html).
So it kinda works like this:

```yaml
  - name: Install configured cask applications.
    community.general.homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: present
      install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
      accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
      sudo_password: "{{ ansible_become_password }}"
    loop: "{{ homebrew_cask_apps }}"
    notify:
      - Clear homebrew cache
```
But that would require some dummy password to be specified in the role, and then it to be overwritten in playbooks using vault, which I think is fine...

What do you guys think?

**Comment by aaraza** [comment]
You can use the `-K` option. This will prompt you to enter a password for commands that require privilege escalation.
https://docs.ansible.com/ansible/latest/cli/ansible.html#cmdoption-ansible-k

**Comment by rounakdatta** [comment]
You can consider using the `ask-become-flag` while using it in a playbook. Example: https://github.com/rounakdatta/computer.setup/blob/master/start.sh#L25

**Comment by kubaraczkowski** [comment]
Could it be that the 'bug' here is that the wrapper created in this repo does not expose (or set) the `sudo_password`? 
It looks like that argument is not set by default to `sudo_password: "{{ ansible_become_pass }}"`

Perhaps there could come a parameter to this role to be passed through to `homebrew_cask` ?
Somewhere here:
https://github.com/geerlingguy/ansible-role-homebrew/blob/master/tasks/main.yml#L111

**Comment by maspotts** [comment]
hi: I'm also facing this issue: I'm trying to install the mactex cask, and the installer hangs because it needs a (sudo?) password.  I tried adding sudo_password: "{{ ansible_become_pass }}" but I get undefined variable error.  The module doesn't seem to support become: true.  I'm very new to ansible so I can't figure out how this problem was solved: would you mind awfully pasting some brief instructions?  This is my current task:

```
    - name: Install mactex
      community.general.homebrew_cask:
        name:
          - mactex
        path: /opt/brew/bin
        state: present
        sudo_password: "{{ ansible_become_password }}"
```

Thanks!
