### ISSUE TITLE
homebrew_tap module fails when moving the homebrew_prefix and brew is not in the path

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-role-homebrew#157]
```
% sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```
```
% python3 -V
Python 3.8.2
```
```
$ ansible --version
ansible 2.9.16.post0
```
Sample playbook that changes `homebrew_prefix` and `homebrew_bin_path` on BigSur ARM
```yaml
- name: macOS Workstation Playbook
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    homebrew_prefix: /opt/homebrew
    homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"
    homebrew_upgrade_all_packages: yes
    homebrew_user: "rte"
    homebrew_group: "staff"
    homebrew_installed_packages:
      - git
  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.homebrew
```
Exception thrown
```
TASK [homebrew : Ensure configured taps are tapped.] ***************************
failed: [macos38.int.celadonsystems.com] (item=homebrew/core) => {"ansible_loop_var": "item", "changed": false, "item": "homebrew/core", "msg": "Failed to find required executable brew in paths: /usr/bin:/bin:/usr/sbin:/sbin"}
```
