### ISSUE TITLE
Homebrew install no longer works due to deprecated repository

### ISSUE THREAD

**Issue by cthachuk** [geerlingguy/ansible-role-homebrew#32]
The repository git://github.com/Homebrew/homebrew.git is now deprecated, causing this role to fail when attempting to install homebrew.  This can be verified by cloning the above repository and reading the README.md file.

Since the hombrew repositories have been split into two parts, I'm not certain what the quick fix is for this role.

**Comment by ksylvan** [comment]
My quick fix was to install `brew` using the curl method (`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`) before running the role.

So the playbook looks like this:

```
# Determine if homebrew is installed and install it if not.
#
- hosts: all
  gather_facts: false
  tasks:
    - name: Determine if brew binary exists
      stat: path=/usr/local/bin/brew
      register: brew_binary
      changed_when: false
    - name: install homebrew
      shell: >
        /usr/bin/ruby -e "$(curl -fsSL
        https://raw.githubusercontent.com/Homebrew/install/master/install)"
        < /dev/null
      when: brew_binary.stat.exists == false

# Install homebrew taps and apps, and any casks specified in variables
#
- hosts: all
  roles:
    - geerlingguy.homebrew
```

You can unpack what the install script is doing with the two github repositories and submit a PR to fix this role in the way that @geerlingguy intended instead of the quick and dirty fix.
