### ISSUE TITLE
Feature suggestion: enable brew services

### ISSUE THREAD

**Issue by ctorgalson** [geerlingguy/ansible-role-homebrew#65]
Hi,

In conjunction with this role, I've been enabling a couple of homebrew services. Would you be interested in incorporating a couple of small tasks and a variable like the following? (If so, I can create a PR.)

```yaml
# Variables.
homebrew_enabled_services:
  - mysql
  - php70
  - syncthing
```

```yaml
# Tasks.
- name: Get currently available brew services.
  shell: "brew services list | sed '1 d' | cut -d ' ' -f 1"
  register: brew_services

- name: Enable brew services.
  command: "brew services start {{ item }}"
  with_items: "{{ homebrew_enabled_services }}"
  when: "'{{ item }}' in brew_services.stdout_lines"
```

I've been using a check (as above) to make sure the service exists, though it might be better to let the task fail when the service is not present.
