### ISSUE TITLE
Wrong group for /usr/local

### ISSUE THREAD

**Issue by DnD-Merlin** [geerlingguy/ansible-role-homebrew#78]
Hello,
I try to use your role with this Playbook https://github.com/fubarhouse/mac-dev-playbook but I have one issue :    
In ` ansible-role-homebrew/tasks/main.yml` you check if the group is `admin`   
```
- name: Ensure Homebrew parent directory has correct permissions (on non-'High Sierra' versions of Mac OS X).
  file:
    path: "{{ homebrew_prefix }}"
    owner: root
    group: admin    <--------
    state: directory
    mode: 0775
  become: yes
when: "not ansible_distribution_version.startswith('10.13')"
```
I would like to know why this value, on the differents Mac I manage they are all at `wheel` group => `root  wheel  /usr/local `     
   
Do I have to change it ? _but not seems to be the right solution_    
or do I have to make a PR to make this value configurable in your role ?   

Thank you.
Matthéo
